import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import AuthButton from "./AuthButton.client";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// how to get the user in layout component
// how to use SessionProvider and keep static sites
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SessionProvider>
        <body className={`${inter.className} dark max-w-3xl mx-auto text-2xl`}>
          <AuthButton />
          {children}
        </body>
      </SessionProvider>
    </html>
  );
}
